### ISSUE TITLE
Constants in parameters of solver.run() method can't have space in their names

### ISSUE THREAD

**Issue by Aluriak** [sthiele/pyasp#2]
Here is the p.py file:

```
from pyasp import asp
solver = asp.Gringo4Clasp(gringo_options='-c v="text with spaces in it"')
solver.run([], additionalProgramText='#const v=1. p(v).')  # error here
```

Here is the stack trace (python 3):

```
Traceback (most recent call last):
  File "p.py", line 6, in <module>
    solver.run([], additionalProgramText='#const v=1. p(v).')
  File "/udd/lbourneu/.local/lib/python3.4/site-packages/pyasp/asp.py", line 383, in run
    grounding = self.__ground__(programs, additionalProgramText)
  File "/udd/lbourneu/.local/lib/python3.4/site-packages/pyasp/asp.py", line 345, in __ground__
    (self._gringo.returncode, self.gringo_stderr))
Exception: got error 1 from gringo: 'b'<v="text>:1:4: error: lexer error, unexpected "\n\n<cmd>: error: file could not be opened:\n  with\n\n<cmd>: error: file could not be opened:\n  spaces\n\n<cmd>: error: file could not be opened:\n  in\n\n<cmd>: error: file could not be opened:\n  it"\n\n*** ERROR: (gringo): grounding stopped because of errors\n''
```

Using gringo CLI, an error appears if supplementary quotes are not provided:

```
gringo4 l.lp -c v='"text with spaces in it"'
```

(with "l.lp" file containing "_#const v=1. p(v)._")

**Comment by sthiele** [comment]
I think I have fixed that issue with using space in quoted text as constants. You can update your branch and test it.

**Comment by Aluriak** [comment]
That's done and fixed, thanks !
